Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -23,8 +23,11 @@ jobs:
     - name: Build with Gradle
       run: ./gradlew build remapJar
 
+    - name: List build/libs
+      run: ls -R build/libs || echo "build/libs not found"
+
     - name: Upload Artifact
       uses: actions/upload-artifact@v4
       with:
         name: fishing-sound-filter
-        path: build/libs/fishing-sound-filter-1.0.0.jar
+        path: build/libs/*.jar
